services:
  api_auth:
    container_name: auth_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_USER}@database_auth:5432/${DATABASE_NAME}
      - REDIS_HOST=redis_auth
      - REDIS_PORT=6379
      - KAFKA_URL=kafka:29092
      - JAEGER_URL=http://jaeger:4318/v1/traces
      - KONG_URL=http://kong:8000
    ports:
      - '3334:3334'
    depends_on:
      - database_auth
    networks:
      - medchatai-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'node -e ''require("http").get("http://localhost:3334/api/health", res => process.exit(res.statusCode === 200 ? 0 : 1))''',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - apis

  database_auth:
    container_name: auth_database
    env_file:
      - .env
    image: 'postgres:15'
    ports:
      - '5456:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - medchatai-network

  redis_auth:
    image: redis:8.2.1
    env_file:
      - .env
    container_name: auth_redis_server
    ports:
      - '6380:6379'
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - medchatai-network
