services:
  api_medchatai:
    container_name: medchatai_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_USER}@database:5432/${DATABASE_NAME}
      - REDIS_HOST=redis_medchatai
      - KAFKA_URL=kafka:29092
      - JAEGER_URL=http://jaeger:4318/v1/traces
      - KONG_URL=http://kong:8000
    ports:
      - '${PORT}:3333'
    depends_on:
      - database
    networks:
      - medchatai-network
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3333/api/health']
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - apis
  database:
    container_name: medchatai_database
    env_file:
      - .env
    image: 'postgres:15'
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - medchatai-network

  redis_medchatai:
    image: redis:8.2.1
    env_file:
      - .env
    container_name: medchatai_redis_server
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - medchatai-network
