name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: postgres
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      zookeeper:
        image: confluentinc/cp-zookeeper:7.3.0
        ports:
          - "2181:2181"
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

      kafka:
        image: confluentinc/cp-server:7.3.0
        ports:
          - "9092:9092"
          - "9094:9094"
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,OUTSIDE:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092,OUTSIDE://host.docker.internal:9094
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          CONFLUENT_METRICS_ENABLE: "false"
          CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://docker:docker@localhost:5432/postgres?schema=public
      DATABASE_USER: docker
      DATABASE_PASSWORD: docker
      DATABASE_NAME: postgres
      DATABASE_PORT: "5432"
      COOKIE_SECRET: test-cookie-secret
      JWT_SECRET: test-jwt-secret
      MAIL_HOST: smtp.test
      MAIL_SECURE: "false"
      MAIL_PORT: "1025"
      MAIL_USER: test
      MAIL_USER_EMAIL: test@test.com
      MAIL_PASSWORD: test
      MAIL_IGNORE_TLS: "true"
      OPENAI_API_KEY: test-openai
      SENTRY_DSN: test-sentry
      CONTACT_EMAIL: contato@medchatai.com
      REDIS_HOST: localhost
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v2
        with:
          version: 10.14.0
      - uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: ./api/pnpm-lock.yaml
      - run: pnpm install
        working-directory: ./api
      - run: pnpm prisma generate
        working-directory: ./api
      - run: pnpm prisma migrate deploy
        working-directory: ./api
      - run: pnpm run test:e2e
        working-directory: ./api
        env:
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/postgres?schema=public"
